
- name: Hello from frontend
  ansible.builtin.debug:
    msg: frontend role


- name: Print variable
  ansible.builtin.debug:
    msg: "{{ samplevar }}"

- name: Install Java
  ansible.builtin.yum:
    name: java-1.8.0-openjdk-devel
    state: latest
    become: yes