- name: Installing Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Import common Role for Code Download
  ansible.builtin.include_role:
    name: common
    tasks_from: download


    #PRINT "Organize ${COMPONENT} Content"
    #mv ${COMPONENT}-main/* . && mv static/* . && rm -rf ${COMPONENT}-main README.md && mv localhost.conf /etc/nginx/default.d/roboshop.conf
    #CHECK_STAT $?
    
    #for backend in catalogue cart user shipping payment ; do
    #PRINT "Update Configuration for - $backend"
    # Commented this as part of loop demo, However this single sed command is much better than loop approach
    # sed -i -e '/catalogue/ s/localhost/catalogue.roboshop.internal/' -e '/user/ s/localhost/user.roboshop.internal/' -e '/cart/ s/localhost/cart.roboshop.internal/' -e '/payment/ s/localhost/payment.roboshop.internal/' -e '/shipping/ s/localhost/shipping.roboshop.internal/' /etc/nginx/default.d/roboshop.conf
    #sed -i -e "/$backend/ s/localhost/$backend.roboshop.internal/" /etc/nginx/default.d/roboshop.conf
    #CHECK_STAT $?
    #done
    
    #PRINT "Start Nginx Service"
    #systemctl enable nginx &>>${LOG} && systemctl restart nginx &>>${LOG}
    #CHECK_STAT $?