
- name: Hello from frontend
  ansible.builtin.debug:
    msg: frontend role

- name: Print myvar "{{ samplevar }}"
  vars_files:
    - variable.yml
  ansible.builtin.debug:
    msg: "{{ samplevar }}"