- name: Setup Yum repo for npm
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x

- name: Install npm
  ansible.builtin.yum:
    name: npm
    state: installed

- name: Import common Role app configuration for npm
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install npm dependencies
  community.general.npm:
    path: "{{ APP_LOCATION }}"
