- name: Setup Yum repo for Nodejs
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import common Role app configuration for Nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install Nodejs dependencies
  community.general.npm:
    path: "{{ APP_LOCATION }}"
