- name: Setup Yum repo for npm
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x

- name: Install npm
  ansible.builtin.yum:
    name: npm
    state: installed

- name: systemD Setup for {{ COMPONENT }} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install npm dependencies
  community.general.npm:
    path: "{{ APP_LOCATION }}"

- name: Setup {{ COMPONENT }} SystemD Service
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: Start {{ COMPONENT }} Service
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    enabled: yes
    state: restated
    daemon_reload: yes
