
- name: Install Setup of Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Import Common App Setup Configurations
  ansible.builtin.include_role:
    name: common
    tasks_from: download

