- name: Restart nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

# in this when we have made some changes in a service then we can restart that machine only by using handlers no need to start all machines by using notify command before starting nginx.